### ISSUE TITLE
Custom element doesn't exist 'hui-vertical-stack-card' new problem

### ISSUE THREAD

**Issue by windsurferwill** [thomasloven/lovelace-hui-element#16]
I have been using -- via HACS -- hui-element as referenced in code: https://community.home-assistant.io/t/ups-system-monitoring-card/266705.  Somewhere between core 11.4 and 12.2 my front-end dashboard shows an error 'Custom element doesn't exist: hui-vertical-stack-card.  I have tried going to HACS-> frontend -> hui-element -> reload to no avail.
![screen shot missing hui-vertical-stack-card](https://user-images.githubusercontent.com/49887431/146645116-249077e1-2be4-4320-ad35-152e3cddde7b.png)
Any ideas?

**Comment by SalvatoreITA** [comment]
With the latest version of home assistant I also have this error! I changed the browser and deleted the cookies but the problem remains

![66](https://user-images.githubusercontent.com/74460788/146650331-a96ad1a3-d558-4b73-bc77-fe4044bb8c8f.PNG)

**Comment by saboaua** [comment]
Same issue here with the last updates. I noticed when you move to a tab and back to the tab that you have the custom card, it loads it without the issue. You hit refresh, you get the error again.

**Comment by ildar170975** [comment]
I guess that this `hui-vertical-stack-card` is an obsolete stuff, is there any special reason not to use a conventional `vertical-stack`?

**Comment by thomasloven** [comment]
Yes... that is exactly the problem hui-element solves. But just installing it is not enough. Please also read the instructions.

**Comment by windsurferwill** [comment]
Hi Thomas,

Happy Holidays to you.  I am still learning Lovelace cards so I 
apologize in advance for my uninformed questions.  I think I remember 
installing via HACS the lovelace-hui-element plugin so that I could get 
the hui-vertical-stack card...this was to support someone else's UPS 
System Monitoring Card 
(https://community.home-assistant.io/t/ups-system-monitoring-card/266705). 
Am I right that lovelace-hui-element contains 
'custom:hui-vertical-stack-card'?

I have tried following your instructions for HACS installation (steps 1 
and 4), but am not making progress in clearing the error.  Would you 
have any additional suggestions I could try?

Thanks in advance.

**Comment by mdezotti** [comment]
I've solved this issue's error by replacing:

```
- type: custom:hui-vertical-stack-card
```
with 

```
- type: custom:hui-element
  card_type: vertical-stack
```
