### ISSUE TITLE
TypeError: o.setConfig is not a function

### ISSUE THREAD

**Issue by Mariusthvdb** [thomasloven/lovelace-hui-element#4]
receiving this:

<img width="719" alt="Schermafbeelding 2020-06-16 om 12 27 34" src="https://user-images.githubusercontent.com/33354141/84829868-c516af00-b028-11ea-9237-99ea9e136726.png">

on views with a core markdown card used through the hui-element custom card. These don't have any link with the referenced hui-weather-forecast-card as far as I can see.

happening on ha 0.111.3 and also issued on the forecast card in [Homeassistant GitHub ](https://github.com/home-assistant/frontend/issues/6169) and Bram thought it to be related to hui-element.

Not sure what config to post here, other than a markdown config for the page happening:

```
type: entities
entities:
  - type: custom:hui-element
    card_type: markdown
    title: |
      Home Assistant --> Google Assistant
      Voice commands
    style: |
      ha-card {background: url('/local/various/google_assistant.png');
               background-size: cover;
               box-shadow: none;
               margin: -16px -16px 0px -16px;
               }
    content: |
      Ok/Hey Google,
      --> <i>'activity/mode'</i> <b>activeren</b>
      --> <b>turn-on/off</b> <i>'switch/verlichting'</i>
      --> <i>'switch/verlichting'</i> <b>in-/uitschakelen</b>
  - type: custom:fold-entity-row
    head:
      type: section
      label: Activities
    padding: 0
    entities:
      - !include /config/lovelace/includes/include_alias_activities.yaml
```

seeing the same error, but also a red card in the frontend every now and then:

<img width="296" alt="Schermafbeelding 2020-06-16 om 23 33 54" src="https://user-images.githubusercontent.com/33354141/84830592-f04dce00-b029-11ea-8fea-95f28b6c3744.png">

```
  - type: entities
    title: Automation & scripts
    style: |
      .card-header {background-color: var(--primary-color);}
    show_header_toggle: false
    entities:
      - type: custom:hui-element
        card_type: markdown
        style: |
          ha-card {
            box-shadow: none;
            margin: 0px -16px 0px -16px;
          }
        content: >
          {{states('sensor.filed_automations')}}
```

final example:

```
type: entities
title: Rss Feeds notification dashboard
show_header_toggle: false
style: |
  .card-header {background-color: var(--primary-color);}
entities:
  - type: custom:hui-element
    card_type: conditional
    conditions:
      - entity: binary_sensor.rss_feeds
        state: 'on'
    card:
      type: custom:hui-element
      card_type: markdown
      style: |
        ha-card {
          box-shadow: none;
          margin: 0px -16px 0px -16px;
        }
      content: >
etcetc
```

please let me know what else to test so this can be examined/solved?

**Comment by tomlut** [comment]
I am also seeing this error and do not use the weather-forecast-card, but do use hui-element for a number of markdown cards.
